### ISSUE TITLE
Runtime error on clean install 

### ISSUE THREAD

**Issue by miller-productions** [vim-labs/gatsby-theme-sky-lite-starter#1]
Hi there,

Just dropping in to take a look at Sky Lite.

Followed instructions [here](https://www.gatsbyjs.org/starters/vim-labs/gatsby-theme-sky-lite-starter/) and in the README.md.

After running `npm install`, then `gatsby develop`, and then launching a browser to `http://localhost:8000/`, I experience the following runtime error.

>×
←→1 of 4 errors on the page
TypeError: Cannot read property 'attach' of undefined
attach
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:119
  116 | var dynamicSheet = stylesOptions.jss.createStyleSheet(sheetManager.dynamicStyles, _extends({
  117 |   link: true
  118 | }, options));
> 119 | dynamicSheet.update(props).attach();
  120 | state.dynamicSheet = dynamicSheet;
  121 | state.classes = mergeClasses({
  122 |   baseClasses: sheetManager.staticSheet.classes,
View compiled
(anonymous function)
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:234
  231 |   stylesOptions: stylesOptions,
  232 |   theme: theme
  233 | };
> 234 | attach(current, props);
  235 | shouldUpdate.current = false;
  236 | instance.current = current;
  237 | return function () {
View compiled
useSynchronousEffect
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:187
  184 | 
  185 | if (key.current !== currentKey) {
  186 |   key.current = currentKey;
> 187 |   output = func();
  188 | }
  189 | 
  190 | React.useEffect(function () {
View compiled
(anonymous function)
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/@material-ui/styles/esm/makeStyles/makeStyles.js:226
  223 | 
  224 | var instance = React.useRef();
  225 | var shouldUpdate = React.useRef();
> 226 | useSynchronousEffect(function () {
  227 |   var current = {
  228 |     name: name,
  229 |     state: {},
View compiled
StyledComponent
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/@material-ui/styles/esm/styled/styled.js:86
  83 |     ComponentProp = props.component,
  84 |     other = _objectWithoutProperties(props, ["children", "className", "clone", "component"]);
  85 | 
> 86 | var classes = useStyles(props);
  87 | var className = clsx(classes.root, classNameProp);
  88 | var spread = other;
  89 | 
View compiled
renderWithHooks
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:16260
  16257 |   }
  16258 | }
  16259 | 
> 16260 | var children = Component(props, refOrContext);
  16261 | 
  16262 | if (didScheduleRenderPhaseUpdate) {
  16263 |   do {
View compiled
updateForwardRef
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:18143
  18140 | {
  18141 |   ReactCurrentOwner$3.current = workInProgress;
  18142 |   setCurrentPhase('render');
> 18143 |   nextChildren = renderWithHooks(current$$1, workInProgress, render, nextProps, ref, renderExpirationTime);
  18144 | 
  18145 |   if (debugRenderPhaseSideEffectsForStrictMode && workInProgress.mode & StrictMode) {
  18146 |     // Only double-render components with Hooks
View compiled
beginWork$1
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:20211
  20208 | 
  20209 |     var _resolvedProps2 = workInProgress.elementType === type ? _unresolvedProps2 : resolveDefaultProps(type, _unresolvedProps2);
  20210 | 
> 20211 |     return updateForwardRef(current$$1, workInProgress, type, _resolvedProps2, renderExpirationTime);
  20212 |   }
  20213 | 
  20214 | case Fragment:
View compiled
HTMLUnknownElement.callCallback
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:336
  333 |     window.event = windowEvent;
  334 |   }
  335 | 
> 336 |   func.apply(context, funcArgs);
  337 |   didError = false;
  338 | } // Create a global error event handler. We use this to capture the value
  339 | // that was thrown. It's possible that this error handler will fire more
View compiled
invokeGuardedCallbackDev
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:385
  382 | // errors, it will trigger our global error handler.
  383 | 
  384 | evt.initEvent(evtType, false, false);
> 385 | fakeNode.dispatchEvent(evt);
  386 | 
  387 | if (windowEventDescriptor) {
  388 |   Object.defineProperty(window, 'event', windowEventDescriptor);
View compiled
invokeGuardedCallback
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:440
  437 | function invokeGuardedCallback(name, func, context, a, b, c, d, e, f) {
  438 |   hasError = false;
  439 |   caughtError = null;
> 440 |   invokeGuardedCallbackImpl$1.apply(reporter, arguments);
  441 | }
  442 | /**
  443 |  * Same as invokeGuardedCallback, but instead of returning an error, it stores
View compiled
beginWork$$1
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:25780
  25777 | } // Run beginWork again.
  25778 | 
  25779 | 
> 25780 | invokeGuardedCallback(null, beginWork$1, null, current$$1, unitOfWork, expirationTime);
  25781 | 
  25782 | if (hasCaughtError()) {
  25783 |   var replayError = clearCaughtError(); // `invokeGuardedCallback` sometimes sets an expando `_suppressLogging`.
View compiled
performUnitOfWork
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:24698
  24695 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  24696 |   stopProfilerTimerIfRunningAndRecordDelta(unitOfWork, true);
  24697 | } else {
> 24698 |   next = beginWork$$1(current$$1, unitOfWork, renderExpirationTime);
  24699 | }
  24700 | 
  24701 | resetCurrentFiber();
View compiled
workLoopSync
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:24671
  24668 | function workLoopSync() {
  24669 |   // Already timed out, so perform work without checking if we need to yield.
  24670 |   while (workInProgress !== null) {
> 24671 |     workInProgress = performUnitOfWork(workInProgress);
  24672 |   }
  24673 | }
  24674 | /** @noinline */
View compiled
performSyncWorkOnRoot
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:24270
  24267 | 
  24268 | do {
  24269 |   try {
> 24270 |     workLoopSync();
  24271 |     break;
  24272 |   } catch (thrownValue) {
  24273 |     handleError(root, thrownValue);
View compiled
scheduleUpdateOnFiber
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:23698
  23695 |   // root inside of batchedUpdates should be synchronous, but layout updates
  23696 |   // should be deferred until the end of the batch.
  23697 | 
> 23698 |   performSyncWorkOnRoot(root);
  23699 | } else {
  23700 |   ensureRootIsScheduled(root);
  23701 |   schedulePendingInteractions(root, expirationTime);
View compiled
updateContainer
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:27103
  27100 |   }
  27101 | 
  27102 |   enqueueUpdate(current$$1, update);
> 27103 |   scheduleWork(current$$1, expirationTime);
  27104 |   return expirationTime;
  27105 | }
  27106 | function getPublicRootInstance(container) {
View compiled
(anonymous function)
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:27528
  27525 | 
  27526 | 
  27527 |   unbatchedUpdates(function () {
> 27528 |     updateContainer(children, fiberRoot, parentComponent, callback);
  27529 |   });
  27530 | } else {
  27531 |   fiberRoot = root._internalRoot;
View compiled
unbatchedUpdates
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:24433
  24430 | executionContext |= LegacyUnbatchedContext;
  24431 | 
  24432 | try {
> 24433 |   return fn(a);
  24434 | } finally {
  24435 |   executionContext = prevExecutionContext;
  24436 | 
View compiled
legacyRenderSubtreeIntoContainer
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:27527
  27524 |   } // Initial mount should not be batched.
  27525 | 
  27526 | 
> 27527 |   unbatchedUpdates(function () {
  27528 |     updateContainer(children, fiberRoot, parentComponent, callback);
  27529 |   });
  27530 | } else {
View compiled
render
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/node_modules/react-dom/cjs/react-dom.development.js:27608
  27605 |     }
  27606 |   }
  27607 | 
> 27608 |   return legacyRenderSubtreeIntoContainer(null, element, container, false, callback);
  27609 | }
  27610 | function unstable_renderSubtreeIntoContainer(parentComponent, element, containerNode, callback) {
  27611 |   if (!isValidContainer(containerNode)) {
View compiled
(anonymous function)
D:/dev/scratch/gatsby/gatsby-theme-sky-lite-starter/.cache/app.js:67
  64 | const preferDefault = m => (m && m.default) || m
  65 | let Root = preferDefault(require(`./root`))
  66 | domReady(() => {
> 67 |   renderer(<Root />, rootElement, () => {
  68 |     apiRunner(`onInitialClientRender`)
  69 |   })
  70 | })
View compiled
This screen is visible only in development. It will not appear if the app crashes in production.
Open your browser’s developer console to further inspect this error.

**Comment by iRyanBell** [comment]
This issue has been resolved (dependency tree updates) in v1.4.0.
