### ISSUE TITLE
gh pages deployment

### ISSUE THREAD

**Issue by masamune-prog** [vim-labs/gatsby-theme-sky-lite-starter#2]
After using npm to setup github pages, following gatsby js instructions by running npm install gh-pages --save-dev
The gatsby develop command cannot be run giving error
Any advice on how to deploy to github pages?

**Comment by iRyanBell** [comment]
You may need to remove the `npm_modules` folder, update to the latest version (1.4.1), and give it a fresh `gatsby develop`. To create a static build, use `gatsby build`.
